name: Validate Databricks Bundle

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    name: Validate DAB
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.base_ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle
        run: databricks bundle validate --target ${{ github.base_ref }}
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}